language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 66ea93551c0aa89eb192c156dcdd5ac0e89344da
 local_dir: dist
 on:
   branch: master
